### ISSUE TITLE
Anonymous Access to the application for Symptom assessment

### ISSUE THREAD

**Issue by SurendraOsti** [samirkarki/MyHealth#5]
Kati paye manche haru le User create garna ani afno details dina ali garo manne dekhiyo so without login test page lai access dinu parla jasto xa, that mean, cred lai optionla gardinu parla baru location line plan garnu parla

**Comment by samirkarki** [comment]
I have updated for anonymous user entry, but the results are not being shown. @technables can you please look on it.

**Comment by technables** [comment]
i have updated for anonymous result page, and also displayed latest result for anonymous user
